// gpu_search_launcher.cpp — Host-side wrapper that resolves and launches
// the per-architecture Freudenthal search kernel on a given GPU device.
//
// Strategy:
//   1. Ask SearchKernelGetLaunchFn_gfx1201() for an AMD launch function.
//   2. If nullptr (no AMD device), ask SearchKernelGetLaunchFn_sm_120()
//      for an NVIDIA launch function.
//   3. If both return nullptr, the requested device supports neither
//      architecture — return failure.
//
// The per-arch SearchKernelRun_<arch> function handles the actual
// hipLaunchKernelGGL call (blockSize=256, auto-computed numBlocks),
// so this wrapper only needs to dispatch to the right symbol.

#include "m4/gpu_search_launcher.h"

// Per-architecture kernel launch functions (generated by gpu_search_kernel.cpp
// via the SEARCH_KERNEL_RUN_NAME macro).  These are C-linkage symbols.
extern "C" {
    typedef int (*SearchKernelRunFn)(int deviceIndex,
                                     const uint8_t* d_primeMap,
                                     uint64_t d_maxPrimeMapValue,
                                     uint64_t d_sumStart,
                                     uint64_t d_sumLimit,
                                     uint32_t* d_pAtomicCount,
                                     GpuRecord* d_pRecords);

    extern SearchKernelRunFn SearchKernelGetLaunchFn_gfx1201(int deviceIndex);
    extern SearchKernelRunFn SearchKernelGetLaunchFn_sm_120(int deviceIndex);
}

int GpuSearchLaunch(int deviceIndex,
                    const uint8_t* d_primeMap,
                    uint64_t d_maxPrimeMapValue,
                    uint64_t d_sumStart,
                    uint64_t d_sumLimit,
                    GpuRecord* d_pRecords,
                    uint32_t* d_pAtomicCount)
{
    // ---- Try AMD (gfx1201) first ----
    SearchKernelRunFn runFn = SearchKernelGetLaunchFn_gfx1201(deviceIndex);
    if (runFn != nullptr) {
        return runFn(deviceIndex,
                     d_primeMap, d_maxPrimeMapValue,
                     d_sumStart, d_sumLimit,
                     d_pAtomicCount, d_pRecords);
    }

    // ---- Fallback to NVIDIA (sm_120) ----
    runFn = SearchKernelGetLaunchFn_sm_120(deviceIndex);
    if (runFn != nullptr) {
        return runFn(deviceIndex,
                     d_primeMap, d_maxPrimeMapValue,
                     d_sumStart, d_sumLimit,
                     d_pAtomicCount, d_pRecords);
    }

    // Neither architecture supports this device.
    return -1;
}