// gpu_search_launcher.cpp — Host-side wrapper that resolves and launches
// the per-architecture Freudenthal search kernel on a given GPU device.
//
// Strategy:
//   1. Dispatch on the caller-supplied VENDOR ("amd" -> gfx1201, "nvidia" ->
//      sm_120).  The runtime index alone is ambiguous because each vendor
//      runtime numbers its devices from 0 — an AMD-first index guess launches
//      the AMD kernel on the AMD device even when the caller allocated the
//      map on the NVIDIA device, causing a cross-device page fault.
//   2. If the vendor's launch function is unavailable (no such device),
//      return failure — the caller degrades to CPU search.
//
// The per-arch SearchKernelRun_<arch> function handles the actual
// hipLaunchKernelGGL call (blockSize=256, auto-computed numBlocks),
// so this wrapper only needs to dispatch to the right symbol.

#include "m4/gpu_search_launcher.h"

#include <cstring>

// Per-architecture kernel launch functions (generated by gpu_search_kernel.cpp
// via the SEARCH_KERNEL_RUN_NAME macro).  These are C-linkage symbols.
extern "C" {
    typedef int (*SearchKernelRunFn)(int deviceIndex,
                                     const uint8_t* d_primeMap,
                                     uint64_t d_maxPrimeMapValue,
                                     uint64_t d_sumStart,
                                     uint64_t d_sumLimit,
                                     uint32_t* d_pAtomicCount,
                                     GpuRecord* d_pRecords);

    extern SearchKernelRunFn SearchKernelGetLaunchFn_gfx1201(int deviceIndex);
    extern SearchKernelRunFn SearchKernelGetLaunchFn_sm_120(int deviceIndex);
}

int GpuSearchLaunch(int deviceIndex,
                    const char* vendor,
                    const uint8_t* d_primeMap,
                    uint64_t d_maxPrimeMapValue,
                    uint64_t d_sumStart,
                    uint64_t d_sumLimit,
                    GpuRecord* d_pRecords,
                    uint32_t* d_pAtomicCount)
{
    // ---- Dispatch by vendor (never guess from the runtime index alone) ----
    SearchKernelRunFn runFn = nullptr;
    if (vendor != nullptr && std::strcmp(vendor, "nvidia") == 0) {
        runFn = SearchKernelGetLaunchFn_sm_120(deviceIndex);
    } else if (vendor != nullptr && std::strcmp(vendor, "amd") == 0) {
        runFn = SearchKernelGetLaunchFn_gfx1201(deviceIndex);
    }

    if (runFn != nullptr) {
        return runFn(deviceIndex,
                     d_primeMap, d_maxPrimeMapValue,
                     d_sumStart, d_sumLimit,
                     d_pAtomicCount, d_pRecords);
    }

    // No launch function for this vendor/device — caller falls back to CPU.
    return -1;
}